name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: egordm/gha-yarn-node-cache@v1

      - name: Install node modules
        run: yarn install

      - name: Report problems
        run: yarn problems

      - name: Run tests
        run: yarn test
